"""added posts and comments tables

Revision ID: 38432cc0ee6f
Revises: 93a9389bab2c
Create Date: 2021-03-06 10:04:46.298470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38432cc0ee6f'
down_revision = '93a9389bab2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('post', sa.Text(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('group_members_group_id_fkey', 'group_members', type_='foreignkey')
    op.create_foreign_key(None, 'group_members', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('locations_group_id_fkey', 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key('locations_group_id_fkey', 'locations', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'group_members', type_='foreignkey')
    op.create_foreign_key('group_members_group_id_fkey', 'group_members', 'groups', ['group_id'], ['id'])
    op.drop_table('comments')
    op.drop_table('posts')
    # ### end Alembic commands ###
