"""created group table linked to locations table

Revision ID: eaabf411e084
Revises: 5081a7a1eadb
Create Date: 2021-03-01 11:16:00.266729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaabf411e084'
down_revision = '5081a7a1eadb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('locations', sa.Column('group_id', sa.Integer(), nullable=True))
    op.alter_column('locations', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'locations', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.alter_column('locations', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('locations', 'group_id')
    op.drop_table('groups')
    # ### end Alembic commands ###
